spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: detection
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shelf-detection2
    username: postgres
    password: admin


server:
  port: 8089


ai-service:
  process-url: "https://c2c9-31-223-46-159.ngrok-free.app"

upload:
  shelf:
    images: uploads/shelf
  rendered:
    images: uploads/rendered_images