spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  application:
    name: detection
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shelf-detection4
    username: postgres
    password: admin


server:
  port: 8089


ai-service:
  process-url: "https://redbird-free-literally.ngrok-free.app/"

